stages:
  data_cleaning:
    cmd: python src/data/data_cleaning.py --force
    deps:
    - data/raw/raw_data.csv
    - src/data/data_cleaning.py
    outs:
    - data/cleaned/cleaned_data.csv
  preprocessing:
    cmd: python src/features/preprocessing.py
    deps:
    - data/cleaned/cleaned_data.csv
    - src/features/preprocessing.py
    outs:
    - data/processed/preprocessed_data.csv
